export const technicalSkills = [
  "figma",
  "adobe xd",
  "sketch",
  "adobe illustrator",
  "photoshop",
  "adobe after effects",
  "canva",
  "invision",
  "zeplin",
  "framer",
  "principle",
  "balsamiq",
  "lottie",
  "material design",
  "human interface guidelines",
  "prototyping",
  "wireframing",
  "user research",
  "accessibility design",
  "motion design",
  "visual hierarchy",
  "typography",
  "branding",
  "color theory",
  "design systems",
  "interaction design",
  "ux writing",
  "information architecture",
  "user journey mapping",
  "html",
  "css",
  "javascript",
  "typescript",
  "react",
  "vue",
  "angular",
  "next.js",
  "node.js",
  "express",
  "tailwind",
  "sass",
  "java",
  "c",
  "c++",
  "c#",
  "python",
  "go",
  "kotlin",
  "swift",
  "dart",
  "docker",
  "kubernetes",
  "jenkins",
  "github actions",
  "ansible",
  "terraform",
  "penetration testing",
  "wireshark",
  "nmap",
  "burp suite",
  "metasploit",
  "linux",
  "bash",
  "powershell",
  "active directory",
  "dns",
  "dhcp",
  "pandas",
  "numpy",
  "tensorflow",
  "scikit-learn",
  "pytorch",
  "jupyter",
  "sql",
  "bigquery",
  "airflow",
  "matplotlib",
  "seaborn",
  "excel",
  "unity",
  "unreal engine",
  "cocos2d",
  "godot",
  "blender",
  "figma",
  "postman",
  "firebase",
  "mongodb",
  "graphql",
  "jira",
  "notion",
  "git",
  "webpack",
  "vite",
  "eslint",
  "prettier",
];

export const nonTechnicalSkills = [
  "communication",
  "leadership",
  "problem solving",
  "critical thinking",
  "teamwork",
  "adaptability",
  "emotional intelligence",
  "conflict resolution",
  "presentation",
  "public speaking",
  "creativity",
  "time management",
  "attention to detail",
  "collaboration",
  "decision making",
  "organization",
  "self motivation",
  "project management",
  "customer service",
  "negotiation",
];
